=== LarsRaschke/TeamBlauge-Server/src/xml/schemas/projectlist_schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="w3.org/2001/XMLSchema-instance"
	attributeFormDefault="unqualified" elementFormDefault="qualified">
	<xs:element name="projectlist" xsi:nil="true">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="projectOverviewEntries" maxOccurs="unbounded"
					minOccurs="0" xsi:nil="true">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="projectname" xsi:nil="true" />
							<xs:element type="xs:string" name="creator" xsi:nil="true" />
							<xs:element type="xs:string" name="createdOn" xsi:nil="true" />
							<xs:element type="xs:string" name="lastMod" xsi:nil="true" />
							<xs:element type="xs:string" name="description" xsi:nil="true" />
							<xs:element name="userEntries" maxOccurs="unbounded"
								minOccurs="0" xsi:nil="true">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:boolean" name="Admin"
												use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:int" name="ID" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== LarsRaschke/TeamBlauge-Server/src/xml/files/_projectlist_BEISPIEL.xml
<?xml version="1.0" encoding="UTF-8"?>
<projectlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/projectlist_schema.xsd">
  <projectOverviewEntries ID="0">
    <projectname>projectname</projectname>
    <creator>creator</creator>
    <createdOn>createdOn</createdOn>
    <lastMod>lastMod</lastMod>
    <description>description</description>
    <userEntries Admin="true">userEntries</userEntries>
  </projectOverviewEntries>
</projectlist>
