=== LarsRaschke/TeamBlauge-Server/src/xml/schemas/projects_schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="w3.org/2001/XMLSchema-instance"
	attributeFormDefault="unqualified" elementFormDefault="qualified">
	<xs:element name="project">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="projectname" xsi:nil="true" />
				<xs:element type="xs:string" name="lastMod" xsi:nil="true" />
				<xs:element type="xs:string" name="description" xsi:nil="true" />
				<xs:element name="taskEntries" maxOccurs="unbounded"
					minOccurs="0" xsi:nil="true">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="taskname" xsi:nil="true" />
							<xs:element type="xs:string" name="statusname" xsi:nil="true" />
							<xs:element type="xs:string" name="lastMod" xsi:nil="true" />
							<xs:element type="xs:string" name="comment" xsi:nil="true" />
							<xs:element type="xs:int" name="color" xsi:nil="true" />
							<xs:element type="xs:string" name="lastUser" xsi:nil="true" />
							<xs:element name="tagEntries" minOccurs="0" maxOccurs="unbounded" xsi:nil="true">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string" />
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:int" name="ID" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element name="statusEntries" maxOccurs="unbounded"
					minOccurs="0" xsi:nil="true">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="status" xsi:nil="true" />
						</xs:sequence>
						<xs:attribute type="xs:int" name="length" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute type="xs:int" name="ID" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== LarsRaschke/TeamBlauge-Server/src/xml/files/projects.xml
<?xml version="1.0" encoding="UTF-8"?>
<project ID="0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/projects_schema.xsd">
  <projectname>projectname</projectname>
  <lastMod>lastMod</lastMod>
  <description>description</description>
  <taskEntries ID="0">
    <taskname>taskname</taskname>
    <statusname>statusname</statusname>
    <lastMod>lastMod</lastMod>
    <comment>comment</comment>
    <color>0</color>
    <lastUser>lastUser</lastUser>
    <tags>tags</tags>
  </taskEntries>
  <statusEntries length="0">
    <status>status</status>
  </statusEntries>
</project>
